#!/bin/sh

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

# Use $XINITRC variable if file exists.
[ -f "$XINITRC" ] && alias startx="startx $XINITRC"

# sudo not required for some system commands
for x in mount umount sv pacman updatedb su ; do
	alias $x="sudo $x"
done

# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	bc="bc -ql" \
	mkd="mkdir -pv" \
	yt="youtube-dl --add-metadata -i" \
	yta="yt -x -f bestaudio/best" \
	r="ranger" \
	ffmpeg="ffmpeg -hide_banner"

# Colorize commands when possible.
alias \
	ls="ls -hN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi"

# These common commands are just too long! Abbreviate them.
alias \
	ka="killall" \
	g="git" \
	trem="transmission-remote" \
	YT="youtube-viewer" \
	sdn="sudo shutdown -h now" \
	e="$EDITOR" \
	v="$EDITOR" \
	sv="sudo $EDITOR" \
	p="sudo pikaur" \
	xi="sudo xbps-install" \
	xr="sudo xbps-remove -R" \
	xq="xbps-query" \
	z="zathura"

alias \
	magit="nvim -c MagitOnly" \
	ref="shortcuts >/dev/null; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/shortcutrc ; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/zshnameddirrc" \
	weath="less -S ${XDG_DATA_HOME:-$HOME/.local/share}/weatherreport" \


# Job related stuff
alias wtconturconnect="ssh fsorokin@10.77.255.229"
alias wtdev="ssh fsorokin@msa-devwt-ap2.whotrades.net"
alias wtworkfolder="cd ~/Documents/programming/whotrades/dev/dev/comon/static/www/"
alias wtsync="rsync -zva --stats -h --no-perms --no-owner --no-group --no-times --exclude=/.git --exclude='node_modules*' --exclude='vendor*' ~/Documents/programming/whotrades/dev/dev/ fsorokin@10.77.255.229:/home/dev/dev && date"
alias gsb="git branch | fzf | xargs git checkout"
alias pi="ssh pi@192.168.1.200"
function wtsf() {
    cd ~/Documents/programming/whotrades/dev/dev/comon/static/www/
    git fetch
    git checkout feature/"$1"
}

alias vpn-up="sudo openconnect --user='fsorokin' -b --pid-file=/var/run/openconnect.pid ra.finam.ru"
alias vpn-down="pgrep openconnect | xargs sudo kill -2"
#
# Some longs commands
alias pim="sudo sshfs pi@192.168.1.200:/mnt /mnt/raspberrypi/ -o allow_other -o default_permissions"

